define: &PI 3.14159265358979323846

sim_time: 100
gravity: [0.0, 0.0, 9.7975]
# nonlinear drag coeffs in surge, roll, nonlinear crossflow drag coeff, linear drag coefficient, scaling factor in surge, scaling factor in roll
dragcoeffs:
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
joint_types:
  - type: SixDOF
  - type: Revolute
    axis: Y
  - type: Revolute
    axis: Z
  - type: Revolute
    axis: Y
  - type: Revolute
    axis: Z
# mass: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
mass: [50.786, 2.64, 87.392, 2.642, 51.119]
# radius: [0.085, 0.085, 0.085, 0.085, 0.085, 0.085, 0.085, 0.085, 0.085]
radius: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
length: [&LL1 1.825, &LL2 0.1, &LL3 2.7865, &LL4 0.1, &LL5 1.244]
fluid_density: 1026.0
parents: [0, 1, 2, 3, 4]
pos_com:
  - [0.99, 0.0, 0.03]
  - [0.05, 0.0, 0.0]
  - [1.41, 0.0, 0.03]
  - [0.05, 0.0, 0.0]
  - [0.71, 0.0, 0.03]
pos_cob:
  - [0.99, 0.0, 0.0]
  - [0.05, 0.0, 0.0]
  - [1.41, 0.0, 0.0]
  - [0.05, 0.0, 0.0]
  - [0.71, 0.0, 0.0]


# translations from frame i-1 to frame i (in frame i-1)
# Note that the offsets corresponding to SixDOF joints can be set to zero
pos_offsets:
  - [0.0, 0.0, 0.0]
  - [*LL1, 0.0, 0.0]
  - [*LL2, 0.0, 0.0]
  - [*LL3, 0.0, 0.0]
  - [*LL4, 0.0, 0.0]
  - [*LL5, 0.0, 0.0]
# [roll (phi), pitch(theta), yaw(psi)] representing R=Rz(psi)*Ry(theta)*Rx(phi)
# R rotates a vector x in frame i into frame i-1
# equivalently, rotates frame i-1 into frame i
roll_pitch_yaw_offsets: # joints axis rotation sequence (relative to body frame)
# z-y-z-y-z-y-z-y
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
thruster_pos_offsets:
  - [0.638, 0,  0.09] # Top aft thruster
  - [0.748,  -0.174,  0.0]
  - [0.638, 0,  -0.09] # Bottom aft
  - [0.748,  -0.174,  0.0]
  - [1.80, 0,  0.09] # Top aft thruster
  - [1.91,  -0.174,  0.0]
  - [1.80, 0,  -0.09] # Bottom aft
  - [1.91,  -0.174,  0.0]
# The direction of the thruster force in link frame
thruster_dirs:
  - [0.0,  1.0,  0.0]
  - [-1.0,  0.0, -1.0]
  - [0.0, -1.0,  0.0]
  - [-1.0,  0.0,  1.0]
  - [0.0,  1.0,  0.0]
  - [-1.0,  0.0, -1.0]
  - [0.0, -1.0,  0.0]
  - [-1.0,  0.0,  1.0]
thruster_parents: [1, 1, 1, 1, 3, 3, 3, 3]
added_mass_coeffs: []
added_alpha: [0.2, 0.2, 0.2, 0.2, 0.2]
