define: &PI 3.14159265358979323846
define: &PI_HALF 1.57079632679489661923
define: &PI_HALF_NEG -1.57079632679489661923

# define: &link_lengths [0.62, 0.1, 0.59, 0.1, 0.80, 0.1, 0.59, 0.1, 0.37]

sim_time: 100
gravity: [0.0, 0.0, 9.7975]
# nonlinear drag coeffs in surge, roll, nonlinear crossflow drag coeff, linear drag coefficient, scaling factor in surge, scaling factor in roll
dragcoeffs: 
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
  - [0.2, 0.1, 0.5, 0.1, 0.1, 0.1]
joint_types:
  - SixDOF
  - Revolute
  - Revolute
  - Revolute
  - Revolute
  - Revolute
  - Revolute
  - Revolute
  - Revolute
# mass: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
mass: []
# radius: [0.085, 0.085, 0.085, 0.085, 0.085, 0.085, 0.085, 0.085, 0.085]
radius: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
length: [&LL1 0.8395, &LL2 0.084, &LL3 1.2760, &LL4 0.084, &LL5 1.618, &LL6 0.084, &LL7 1.2760, &LL8 .084, &LL9 0.6045]
fluid_density: 1026.0
parents: [0, 1, 2, 3, 4, 5, 6, 7, 8]
pos_com:
  - [0.41975, 0.0, 0.03]
  - [0.042, 0.0, 0.0]
  - [0.638, 0.0, 0.03]
  - [0.042, 0.0, 0.0]
  - [0.809, 0.0, 0.03]
  - [0.042, 0.0, 0.0]
  - [0.638, 0.0, 0.03]
  - [0.042, 0.0, 0.0]
  - [0.30225, 0.0, 0.03]
pos_cob:
  - [0.41975, 0.0, 0.0]
  - [0.042, 0.0, 0.0]
  - [0.638, 0.0, 0.0]
  - [0.042, 0.0, 0.0]
  - [0.809, 0.0, 0.0]
  - [0.042, 0.0, 0.0]
  - [0.638, 0.0, 0.0]
  - [0.042, 0.0, 0.0]
  - [0.30225, 0.0, 0.0]

# translations from frame i-1 to frame i (in frame i-1)
# Note that the offsets corresponding to SixDOF joints can be set to zero
pos_offsets:
  - [0.0, 0.0, 0.0]
  - [*LL1, 0.0, 0.0]
  - [*LL2, 0.0, 0.0]
  - [*LL3, 0.0, 0.0]
  - [*LL4, 0.0, 0.0]
  - [*LL5, 0.0, 0.0]
  - [*LL6, 0.0, 0.0]
  - [*LL7, 0.0, 0.0]
  - [*LL8, 0.0, 0.0]
# [roll (phi), pitch(theta), yaw(psi)] representing R=Rz(psi)*Ry(theta)*Rx(phi)
# R rotates a vector x in frame i into frame i-1
# equivalently, rotates frame i-1 into frame i
roll_pitch_yaw_offsets: # joints axis rotation sequence (relative to body frame)
# z-y-z-y-z-y-z-y
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]           
  - [*PI_HALF_NEG, 0.0, 0.0]  
  - [*PI_HALF, 0.0, 0.0]      
  - [*PI_HALF_NEG, 0.0, 0.0]
  - [*PI_HALF, 0.0, 0.0]
  - [*PI_HALF_NEG, 0.0, 0.0]
  - [*PI_HALF, 0.0, 0.0]
  - [*PI_HALF_NEG, 0.0, 0.0]
thruster_pos_offsets:
  - [0.3645, -0.174,  0.0]
  - [0.3645,  0.174,  0.0]
  - [0.4745,  0.000,  0.09]
  - [0.4745,  0.000, -0.09]
  - [0.8665, -0.174,  0.0]
  - [0.8665,  0.174,  0.0]
  - [0.7565,  0.000,  0.09]
  - [0.7565,  0.000, -0.09]
  - [0.9115, -0.174,  0.00]
  - [0.9115,  0.174,  0.00]
  - [0.8015,  0.000, -0.09]
  - [0.8015,  0.000,  0.09]
# The direction of the thruster force in link frame
thruster_dirs:
  - [1.0,  0.0, -1.0]
  - [1.0,  0.0,  1.0]
  - [0.0,  1.0,  0.0]
  - [0.0, -1.0,  0.0]
  - [1.0,  0.0,  0.0]
  - [1.0,  0.0,  0.0]
  - [0.0,  1.0,  0.0]
  - [0.0, -1.0,  0.0]
  - [1.0,  0.0,  1.0]
  - [1.0,  0.0, -1.0]
  - [0.0,  1.0,  0.0]
  - [0.0, -1.0,  0.0]
thruster_parents: [1, 1, 1, 1, 3, 3, 3, 3, 6, 6, 6, 6]
# thruster_parents: [2, 2, 3, 3, 3, 4, 4]
added_mass_coeffs: []
added_alpha: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]